stages:
  - build
  - test

build:
  stage: build
  image: composer
  script:
    - composer install
  artifacts:
    paths: 
      - vendor/

test-quality-standards:
  stage: test
  image: php:latest
  script:
    - vendor/bin/phpstan
    - vendor/bin/phpcs

test-php7:
  stage: test
  image: php:7
  script:
    - vendor/bin/phpunit

test-php8:
  stage: test
  image: php:8
  script:
    - vendor/bin/phpunit
