name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: Test with phpunit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1']
        
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5 # or alternative dependency management
    - uses: php-actions/phpunit@v3
