name: TicketBai Actions
on: [push]
jobs:
  phpstan:
    name: Check with phpstan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: gmp, curl, gd
    - name: checkout
      uses: actions/checkout@v2
    - name: composer
      uses: php-actions/composer@v5 # or alternative dependency management
      with:
        php_version: ${{ matrix.php-versions }}
        php_extensions: gmp curl gd
    - name: phpstan
      uses: php-actions/phpstan@v3
      with:
        php_version: ${{ matrix.php-versions }}
        php_extensions: gmp curl gd
        configuration: phpstan.neon
        memory_limit: 1G

  phpunit:
    name: Test with phpunit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    env:
      TBAI_ARABA_APP_LICENSE: ${{ secrets.TBAI_ARABA_APP_LICENSE }}
      TBAI_ARABA_APP_DEVELOPER_NIF: ${{ secrets.TBAI_ARABA_APP_DEVELOPER_NIF }}
      TBAI_BIZKAIA_APP_DEVELOPER_NIF: ${{ secrets.TBAI_BIZKAIA_APP_DEVELOPER_NIF }}
      TBAI_BIZKAIA_ISSUER_NAME_140: ${{ secrets.TBAI_BIZKAIA_ISSUER_NAME_140 }}
      TBAI_BIZKAIA_ISSUER_NIF_140: ${{ secrets.TBAI_BIZKAIA_ISSUER_NIF_140 }}
      TBAI_BIZKAIA_ISSUER_NAME_240: ${{ secrets.TBAI_BIZKAIA_ISSUER_NAME_240 }}
      TBAI_BIZKAIA_ISSUER_NIF_240: ${{ secrets.TBAI_BIZKAIA_ISSUER_NIF_240 }}
      TBAI_GIPUZKOA_APP_LICENSE: ${{ secrets.TBAI_GIPUZKOA_APP_LICENSE }}
      TBAI_GIPUZKOA_APP_DEVELOPER_NIF: ${{ secrets.TBAI_GIPUZKOA_APP_DEVELOPER_NIF }}

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: gmp, curl, gd
        tools: phpunit, composer, openssl
    - name: checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Run phpunit
      run: phpunit -c phpunit.xml.dist --filter "^(?!.*(araba)).*$"
